// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpmyrsdegyouehzdzxhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwbXlyc2RlZ3lvdWVoemR6eGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTM3NzAsImV4cCI6MjA2NjM4OTc3MH0.p0jDtYJtTK6HjMVFure1M6qd9CQYXUlgztbqeDOB1q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);